name: Deploy to Render

on:
  push:
    branches:
      - master  # 或你設定的部署分支

jobs:
  deploy:
    name: Trigger Render Deploy Hook
    runs-on: ubuntu-latest

    steps:
      - name: Call Render deploy webhook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
